### ISSUE TITLE
사진 3d로 띄우기

### ISSUE THREAD

**Issue by yejineee** [yejineee/yangs-in-jeju#5]
# AC
- [x] 3d로 띄워져있는 사진이 있다.
- [x] 사진 주위를 섬이 감싼다. 
- [x] 사진(or something)을 클릭하면, 사진이 확대된다.
- [x] 확대된 상태에서 옆 화살표를 눌러 사진을 이동시킬 수 있다.
